// Automatically generated by the bundler tool from c:\Documents and Settings\mvelegonda\Desktop\Copy of Portal2DGame\Portal2DGame\Portal2DGame\resource2.rdf

#define resource_NUM_RESOURCES 5UL

#define resource_level7_OFFSET 0UL
#define resource_level8_OFFSET 20UL
#define resource_level9_OFFSET 40UL
#define resource_level10_OFFSET 60UL
#define resource_turret_OFFSET 80UL
