// Automatically generated by the bundler tool from c:\Documents and Settings\mvelegonda\Desktop\Copy of Portal2DGame\Portal2DGame\Portal2DGame\resource.rdf

#define resource_NUM_RESOURCES 10UL

#define resource_level1_OFFSET 0UL
#define resource_level2_OFFSET 20UL
#define resource_level3_OFFSET 40UL
#define resource_level4_OFFSET 60UL
#define resource_level5_OFFSET 80UL
#define resource_level6_OFFSET 100UL
#define resource_player_OFFSET 120UL
#define resource_crossHair_OFFSET 140UL
#define resource_spriteSheet_OFFSET 160UL
#define resource_turret_OFFSET 180UL
