#ifndef __XACT_PROJECT_PORTALSFX__
#define __XACT_PROJECT_PORTALSFX__

typedef enum
{
    XACT_WAVEBANK_MEDIASOUNDBANK_COULD_YOU_COME_OVER_HERE = 0,
    XACT_WAVEBANK_MEDIASOUNDBANK_HELLO_FRIEND_ = 1,
    XACT_WAVEBANK_MEDIASOUNDBANK_I_DONT_HATE_YOU = 2,
    XACT_WAVEBANK_MEDIASOUNDBANK_I_SEE_YOU = 3,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTAL_AMBIENT_LOOP1 = 4,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTAL_CLOSE1 = 5,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTAL_FIZZLE2 = 6,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTAL_INVALID_SURFACE3 = 7,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTALGUN_POWERUP1 = 8,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTALGUN_SHOOT_BLUE1 = 9,
    XACT_WAVEBANK_MEDIASOUNDBANK_PORTALGUN_SHOOT_RED1 = 10,
    XACT_WAVEBANK_MEDIASOUNDBANK_STILL_ALIVE_RADIOREMIX = 11,
    XACT_WAVEBANK_MEDIASOUNDBANK_STILL_ALIVE = 12,
    XACT_WAVEBANK_MEDIASOUNDBANK_STEPS = 13,
    XACT_WAVEBANK_MEDIASOUNDBANK_NEWSTEPS = 14,
} XACT_WAVEBANK_MEDIASOUNDBANK;

#define XACT_WAVEBANK_MEDIASOUNDBANK_ENTRY_COUNT 15

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_BACKGROUND = 0,
    XACT_SOUNDBANK_SFXBANK_STILLALIVE = 1,
    XACT_SOUNDBANK_SFXBANK_INVALIDPORTAL = 2,
    XACT_SOUNDBANK_SFXBANK_SHOOTPORTAL = 3,
    XACT_SOUNDBANK_SFXBANK_LEVELCOMPLETE = 4,
    XACT_SOUNDBANK_SFXBANK_COMEOVER = 5,
    XACT_SOUNDBANK_SFXBANK_HELLO = 6,
    XACT_SOUNDBANK_SFXBANK_IDONTHATEYOU = 7,
    XACT_SOUNDBANK_SFXBANK_SEEYOU = 8,
    XACT_SOUNDBANK_SFXBANK_CLOSEPORTAL = 9,
    XACT_SOUNDBANK_SFXBANK_FIZZLEPORTAL = 10,
    XACT_SOUNDBANK_SFXBANK_ALIVEREMIX = 11,
    XACT_SOUNDBANK_SFXBANK_STEPS = 12,
} XACT_SOUNDBANK_SFXBANK;

#define XACT_SOUNDBANK_SFXBANK_CUE_COUNT 13

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_BACKGROUND_SOUND_BACKGROUND = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_BACKGROUND_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_BACKGROUND_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_STILLALIVE_SOUND_STILLALIVE = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_STILLALIVE_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_STILLALIVE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_INVALIDPORTAL_SOUND_INVALIDPORTAL = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_INVALIDPORTAL_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_INVALIDPORTAL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_SHOOTPORTAL_SOUND_SHOOTPORTAL = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_SHOOTPORTAL_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_SHOOTPORTAL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_LEVELCOMPLETE_SOUND_LEVELCOMPLETE = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_LEVELCOMPLETE_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_LEVELCOMPLETE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_COMEOVER_SOUND_COMEOVER = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_COMEOVER_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_COMEOVER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_HELLO_SOUND_HELLO = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_HELLO_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_HELLO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_IDONTHATEYOU_SOUND_IDONTHATEYOU = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_IDONTHATEYOU_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_IDONTHATEYOU_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_SEEYOU_SOUND_SEEYOU = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_SEEYOU_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_SEEYOU_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_CLOSEPORTAL_SOUND_CLOSEPORTAL = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_CLOSEPORTAL_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_CLOSEPORTAL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_FIZZLEPORTAL_SOUND_FIZZLEPORTAL = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_FIZZLEPORTAL_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_FIZZLEPORTAL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_ALIVEREMIX_SOUND_ALIVEREMIX = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_ALIVEREMIX_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_ALIVEREMIX_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_CUE_STEPS_SOUND_STEPS = 0,
} XACT_SOUNDBANK_SFXBANK_CUE_STEPS_SOUND;

#define XACT_SOUNDBANK_SFXBANK_CUE_STEPS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_STEPS_TRACK_0_WAVE_NEWSTEPS = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_STEPS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_STEPS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_BACKGROUND_TRACK_0_WAVE_PORTAL_AMBIENT_LOOP1 = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_BACKGROUND_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_BACKGROUND_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_STILLALIVE_TRACK_0_WAVE_STILL_ALIVE = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_STILLALIVE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_STILLALIVE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_INVALIDPORTAL_TRACK_0_WAVE_PORTAL_INVALID_SURFACE3 = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_INVALIDPORTAL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_INVALIDPORTAL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_SHOOTPORTAL_TRACK_0_WAVE_PORTALGUN_SHOOT_RED1 = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_SHOOTPORTAL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_SHOOTPORTAL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_LEVELCOMPLETE_TRACK_0_WAVE_PORTALGUN_POWERUP1 = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_LEVELCOMPLETE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_LEVELCOMPLETE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_COMEOVER_TRACK_0_WAVE_COULD_YOU_COME_OVER_HERE = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_COMEOVER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_COMEOVER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_HELLO_TRACK_0_WAVE_HELLO_FRIEND_ = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_HELLO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_HELLO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_IDONTHATEYOU_TRACK_0_WAVE_I_DONT_HATE_YOU = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_IDONTHATEYOU_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_IDONTHATEYOU_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_SEEYOU_TRACK_0_WAVE_I_SEE_YOU = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_SEEYOU_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_SEEYOU_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_CLOSEPORTAL_TRACK_0_WAVE_PORTAL_CLOSE1 = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_CLOSEPORTAL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_CLOSEPORTAL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_FIZZLEPORTAL_TRACK_0_WAVE_PORTAL_FIZZLE2 = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_FIZZLEPORTAL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_FIZZLEPORTAL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SFXBANK_SOUND_ALIVEREMIX_TRACK_0_WAVE_STILL_ALIVE_RADIOREMIX = 0,
} XACT_SOUNDBANK_SFXBANK_SOUND_ALIVEREMIX_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SFXBANK_SOUND_ALIVEREMIX_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_CATEGORY_FOOSTEPS = 0,
    XACT_CATEGORY_BACKGROUND = 1,
    XACT_CATEGORY_SFX = 2,
    XACT_CATEGORY_VOICE = 3,
} XACT_CATEGORY;

#define XACT_CATEGORY_COUNT 4

#endif // __XACT_PROJECT_PORTALSFX__
